### ISSUE TITLE
Maui Shell fails to build with clang-13: error: linker command failed in Fedora 35 

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Nitrux/maui-shell#10]
**Describe the bug**
I have a linker error while trying to build `MAUI-Shell`
```
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/cask.dir/build.make:349: bin/cask] Error 1
make[2]: Leaving directory '/home/voidflow/MAUI-Shell/maui-shell/build'
make[1]: *** [CMakeFiles/Makefile2:626: src/CMakeFiles/cask.dir/all] Error 2
make[1]: Leaving directory '/home/voidflow/MAUI-Shell/maui-shell/build'
make: *** [Makefile:149: all] Error 2
```

**Expected behavior**
A perfect `make` process

**Screenshots**
![image](https://user-images.githubusercontent.com/49131888/147876488-cc7470f9-eacb-4170-86c4-2f1282a6c017.png)

**Desktop (please complete the following information):**
```
OS: Fedora 35 (VM in VirtualBox 6.1.30)
Plasma: 5.22.5
Compiler: clang 13.0.0
```

**Comment by UriHerrera** [comment]
Maui Shell cannot be built in Fedora currently (see wiki). We'll revisit the instructions in the wiki once Fedora includes the necessary packages to compile the dependencies of Maui Shell.

For now, I'm closing this issue.
