### ISSUE TITLE
Missing two dependencies for Debian (If you compile from source code)

### ISSUE THREAD

**Issue by 0n1cOn3** [Nitrux/maui-shell#12]
**Describe the bug**
Missing dependencies for maui-shell from source code. aswell missing qml packages to execute maui-shell

**To Reproduce**
1. Using Debian 11
2. Cloned Github Repo and started to install all dependencies
3. There missing dependencies for Debian builds from Source Code

**Expected behavior**
Clean compiling

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kaisen Linux (Debian 11 Fork)
 - Browser: Not required for compiling maui-shell
 - Version: 2.0 Rolling Release (Debian 11 testing)
 
 Additional dependecies where not listed, which maybe could added to the README.md:
 
 - libcanberra-dev
 - libpulse-dev
 - qml-module-qtwayland-compositor
 - qml-module-qtquick-shapes

**Comment by 0n1cOn3** [comment]
To execute Maui Shell, the packagee "qml-module-qtwayland-compositor" is aswell required.
Thats the Log output after starting maui shell without it:

1 96.1263 141.951 QRect(0,0 1920x1044) QSize(1920, 1044) QSize(1920, 1044)
Screen "eDP-1" QRect(0,0 1920x1080) QSizeF(344, 193) DPI: log 96.1263 phys 141.951 DPR 1
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:5:1: module "QtWayland.Compositor" is not installed
Icon theme "mate" not found.

**Comment by UriHerrera** [comment]
Added packages to the readme.
