### ISSUE TITLE
Replace or remove wallpaper files in this repository

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/maui-shell#16]
The wallpapers in this repository are of an unknown license, origin, and author, and they __should not__ be part of the contents of this repository, nor should they be referenced in the source code of the shell.

**Comment by marek-lach** [comment]
> The wallpapers in this repository are of an unknown license, origin, and author, and they **should not** be part of the contents of this repository, nor should they be referenced in the source code of the shell.

Are they not https://github.com/Nitrux/nitrux-wallpapers-free? I suppose the license then would be [creative commons](https://github.com/Nitrux/nitrux-wallpapers-free/blob/master/LICENSE), though perhaps it should be added into the wallpapers directory here...?

**Comment by UriHerrera** [comment]
> > The wallpapers in this repository are of an unknown license, origin, and author, and they **should not** be part of the contents of this repository, nor should they be referenced in the source code of the shell.
> 
> Are they not https://github.com/Nitrux/nitrux-wallpapers-free? I suppose the license then would be [creative commons](https://github.com/Nitrux/nitrux-wallpapers-free/blob/master/LICENSE), though perhaps it should be added into the wallpapers directory here...?

No, they're not ours. Contributors donated some of the wallpapers in that repository, or their licenses are permissive for inclusion; we don't know what license these wallpapers use.
