### ISSUE TITLE
invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]

### ISSUE THREAD

**Issue by aymanrgab** [Nitrux/maui-shell#19]
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp: In member function ‘void WindowBlur::updateBlur()’:
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:135:42: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  135 |         KWindowEffects::enableBlurBehind(m_view, m_enabled);
      |                                          ^~~~~~
      |                                          |
      |                                          QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from /home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:31:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:119:48: note:   initializing argument 1 of ‘void KWindowEffects::enableBlurBehind(WId, bool, const QRegion&)’
  119 | KWINDOWSYSTEM_EXPORT void enableBlurBehind(WId window, bool enable = true, const QRegion &region = QRegion());
      |                                            ~~~~^~~~~~
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:136:50: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  136 |         KWindowEffects::enableBackgroundContrast(m_view, m_enabled);
      |                                                  ^~~~~~
      |                                                  |
      |                                                  QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from /home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:31:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:140:56: note:   initializing argument 1 of ‘void KWindowEffects::enableBackgroundContrast(WId, bool, qreal, qreal, qreal, const QRegion&)’
  140 | KWINDOWSYSTEM_EXPORT void enableBackgroundContrast(WId window, bool enable = true, qreal contrast = 1, qreal intensity = 1, qreal saturation = 1, const QRegion &region = QRegion());
      |                                                    ~~~~^~~~~~
make[2]: *** [src/CMakeFiles/MauiKit.dir/build.make:1060: src/CMakeFiles/MauiKit.dir/platforms/linux/blurhelper/windowblur.cpp.o] Error 1
make[2]: Leaving directory '/home/ayman/mauikit/build'
make[1]: *** [CMakeFiles/Makefile2:370: src/CMakeFiles/MauiKit.dir/all] Error 2
make[1]: Leaving directory '/home/ayman/mauikit/build'
make: *** [Makefile:163: all] Error 2

**Comment by UriHerrera** [comment]
Please use Issues>New issues>Bug report and fill your bug report adequately.
