### ISSUE TITLE
Error in Compile MauiKit

### ISSUE THREAD

**Issue by aymanrgab** [Nitrux/maui-shell#20]
error: invalid conversion from ‘QWindow*’ to ‘WId’

[ 31%] Building CXX object src/CMakeFiles/MauiKit.dir/platforms/linux/blurhelper/windowblur.cpp.o
cd /home/ayman/mauikit/build/src && /usr/bin/c++ -DKCOREADDONS_LIB -DMauiKit_EXPORTS -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQUICK_COMPILER -I/home/ayman/mauikit/build/src -I/home/ayman/mauikit/src -I/home/ayman/mauikit/build/src/MauiKit_autogen/include -I/home/ayman/mauikit/src/utils -I/home/ayman/mauikit/build/src/utils -I/home/ayman/mauikit/src/utils/models -I/home/ayman/mauikit/build/src/utils/models -I/home/ayman/mauikit/src/utils/model_template -I/home/ayman/mauikit/build/src/utils/model_template -I/home/ayman/mauikit/src/controls/libs -I/home/ayman/mauikit/build/src/controls/libs -I/home/ayman/mauikit/src/platforms -I/home/ayman/mauikit/build/src/platforms -I/home/ayman/mauikit/src/platforms/linux -I/home/ayman/mauikit/build/src/platforms/linux -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KNotifications -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtQmlModels -O3 -DNDEBUG -fPIC -fPIC -std=gnu++17 -o CMakeFiles/MauiKit.dir/platforms/linux/blurhelper/windowblur.cpp.o -c /home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp: In member function ‘void WindowBlur::updateBlur()’:
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:135:42: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  135 |         KWindowEffects::enableBlurBehind(m_view, m_enabled);
      |                                          ^~~~~~
      |                                          |
      |                                          QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from /home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:31:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:119:44: note:   initializing argument 1 of ‘void KWindowEffects::enableBlurBehind(WId, bool, const QRegion&)’
  119 | KWINDOWSYSTEM_EXPORT void enableBlurBehind(WId, bool enable = true, const QRegion &region = QRegion());
      |                                            ^~~
/home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:136:50: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  136 |         KWindowEffects::enableBackgroundContrast(m_view, m_enabled);
      |                                                  ^~~~~~
      |                                                  |
      |                                                  QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from /home/ayman/mauikit/src/platforms/linux/blurhelper/windowblur.cpp:31:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:140:56: note:   initializing argument 1 of ‘void KWindowEffects::enableBackgroundContrast(WId, bool, qreal, qreal, qreal, const QRegion&)’
  140 | KWINDOWSYSTEM_EXPORT void enableBackgroundContrast(WId window, bool enable = true, qreal contrast = 1, qreal intensity = 1, qreal saturation = 1, const QRegion &region = QRegion());
      |                                                    ~~~~^~~~~~
make[2]: *** [src/CMakeFiles/MauiKit.dir/build.make:1060: src/CMakeFiles/MauiKit.dir/platforms/linux/blurhelper/windowblur.cpp.o] Error 1
make[2]: Leaving directory '/home/ayman/mauikit/build'
make[1]: *** [CMakeFiles/Makefile2:370: src/CMakeFiles/MauiKit.dir/all] Error 2
make[1]: Leaving directory '/home/ayman/mauikit/build'
make: *** [Makefile:163: all] Error 2

**Comment by UriHerrera** [comment]
Please use Issues>New issue>Bug report.

Fill your bug report adequately and format console output properly. __Please follow the instructions, or any new issues will be subsequently closed__.
