### ISSUE TITLE
Error building MauiKit to compile Maui Shell in Ubuntu 20.04

### ISSUE THREAD

**Issue by aymanrgab** [Nitrux/maui-shell#21]
**Describe the bug**
`make` stops at `invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]` error.

**To Reproduce**

- Follow [Build instructions for Ubuntu 20.04](https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Ubuntu-20.04)
- Run `make` for MauiKit

**Expected behavior**
Compile MauiKit without errors to proceed with installing MauiKit FileBrowsing and Maui Shell.

**Screenshots**
![Screenshot from 2022-01-22 23-15-48](https://user-images.githubusercontent.com/45921642/150656189-2ca37b04-8ec1-4595-82d2-fc35b3060240.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by aymanrgab** [comment]
don't close issue :)

**Comment by UriHerrera** [comment]
I updated the instructions in the Wiki. You will need to add the KDE Neon user repository as the KF5 libraries need to be newer than 5.80.0. Else MauiKit and everything else will fail to compile.

**Comment by dudeisbrendan03** [comment]
Any tips on getting those packages + dependencies on 20.04?

**Comment by UriHerrera** [comment]
> Any tips on getting those packages + dependencies on 20.04?

https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Ubuntu#ubuntu-2004

**Comment by UriHerrera** [comment]
Wiki updated.
