### ISSUE TITLE
Error in package name in Build Instructions for Fedora 35 

### ISSUE THREAD

**Issue by aymanrgab** [Nitrux/maui-shell#22]
**Describe the bug**
kf5-k18n-devel should be kf5-ki18n-devel
**To Reproduce**
1. Build Instructions for Fedora 35 
2. KF5 Dependencies
3. sudo dnf install kf5-k18n-devel

**Expected behavior**
correct misspelling 
**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Fedora 35

**Comment by UriHerrera** [comment]
[Fixed](https://github.com/Nitrux/maui-shell/wiki/Build-Instructions-for-Fedora-35/7b41ca352e9635a5958089435ab37737230a9527)
