### ISSUE TITLE
Start cask session can be terminated with Ctrl+C

### ISSUE THREAD

**Issue by milohr** [Nitrux/maui-shell#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by Vistaus** [comment]
Isn't that fixed in https://github.com/Nitrux/maui-shell/commit/8b5639c94828eaec026e85b8e6000bea169f3e67?

**Comment by milohr** [comment]
fixed
