### ISSUE TITLE
Maui Shell is not displayed after executing the latest AppImage

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Nitrux/maui-shell#28]
**Describe the bug**
Downloaded `maui-shell-latest-x86_64.AppImage` does not graphically appear after executing it.

**To Reproduce**
1. Download Maui Shell Appimage
2. Execute it.

**Expected behavior**
Maui Shell is displayed.

**Desktop (please complete the following information):**
 - OS:  Fedora Rawhide
 
 **Additional context**
 This is the output when I execute it on a terminal.
 
```
[root@BEEDELLROKEJULIANLOCKHART /]# /root/Downloads/maui-shell-latest-x86_64.AppImage
CREATING INSTANCE OF MAUI APP
"maui-style"
1 96.0236 87.5731 QRect(0,0 2560x1440) QSize(2560, 1440) QSize(2560, 1440)
QCommandLineParser: already having an option named "h"
QCommandLineParser: already having an option named "help-all"
QCommandLineParser: already having an option named "v"
Screen "HDMI-A-0" QRect(0,0 2560x1440) QSizeF(725, 428) DPI: log 96.0236 phys 87.5731 DPR 1
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffcae9e6fa0), parent's thread is QThread(0x55beb7522940), current thread is QThread(0x55beb75fea70)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Icon theme "breeze-dark" not found.
Icon theme "breeze" not found.
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:19:5: Type Screen unavailable
qrc:/qml/Screen.qml:111:32: Type StatusBar unavailable
qrc:/qml/shell/statusbar/StatusBar.qml:203:13: Type SlidersItem unavailable
qrc:/qml/shell/statusbar/items/sliders/SlidersItem.qml:64:17: Type VolumeSlider unavailable
qrc:/qml/shell/statusbar/items/sliders/volume/VolumeSlider.qml:13:1: plugin cannot be loaded for module "org.kde.plasma.private.volume": Cannot load library /tmp/.mount_maui-sXCUMpX/usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/private/volume/libplasma-volume-declarative.so:
```

**Comment by UriHerrera** [comment]
Please add the output of `lshw -class display` to your issue (and ***please*** format it).

**Comment by cniw** [comment]
The verbose messages says that it can't load `libplasma-volume-declarative.so` which is provided by `plasma-pa` package and from what i've read the appimage-builder recipe it seem already there https://github.com/Nitrux/maui-shell/blob/c221bc1b535c3e291cbea04b4a3426811dc08439/maui-shell-appimage.yml#L61

@BEEDELLROKEJULIANLOCKHART for temporary solution maybe you can install that package from your package manager `sudo dnf install plasma-pa` and btw why did you run it with root user instead of normal (un-root) user?

 @probal31 just mention, maybe you're right person related to this issue

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@cniw, I utilise PID-0 as my main account, because how I manage this computer does not necessitate the security that "normal" user-accounts inherently provide.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@UriHerrera, is your instruction to differently format what I have posted, or to format what I shall?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@UriHerra, the consequence of execution of "lshw -class display" is:
```
[root@BEEDELLROKEJULIANLOCKHART ~]# lshw -class display
  *-display                 
       description: VGA compatible controller
       product: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:09:00.0
       logical name: /dev/fb0
       version: c4
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=amdgpu latency=0 mode=2560x1440 visual=truecolor xres=2560 yres=1440
       resources: iomemory:7c0-7bf iomemory:7e0-7df irq:129 memory:7c00000000-7dffffffff memory:7e00000000-7e0fffffff ioport:e000(size=256) memory:fcd00000-fcd7ffff memory:fcd80000-fcd9ffff
[root@BEEDELLROKEJULIANLOCKHART ~]#
```
Is your instruction to modify how what I have posted has been formatted, or to differently format what I shall post?

**Comment by djypku** [comment]
Similar prob;em on Fedora 36 KDE (Kinoite). Seems that appimage not works on Fedora 36

**Comment by abiinkunlovescats** [comment]
Try building it instead of using the AppImage.

**Comment by probal31** [comment]
Hello @BEEDELLROKEJULIANLOCKHART ,

Can you please check once if the latest maui shell appimage runs in the fedora environment?
https://github.com/Nitrux/maui-shell/releases/download/latest/maui-shell-latest-x86_64.AppImage

Thanks.
