### ISSUE TITLE
fedora36/cmake: Missing devel packages in Wiki instructions

### ISSUE THREAD

**Issue by thetredev** [Nitrux/maui-shell#33]
**Describe the bug**
Not really a software bug per se, but the Wiki lacks a few packages needed to build the software on Fedora (36). I'll post them here at the end of this report.

**To Reproduce**
Follow https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Fedora-35 up until https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Fedora-35#compile-maui-shell-needs-mauikit-and-mauikit-filebrowsing. The `cmake` part will fail (at least on Fedora 36, don't know about Fedora 35).

**Expected behavior**
CMake executes without any errors.

**Screenshots**
No screenshots, but I'll post an exemplary error message:
```cmake
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: Su ItemModels Init TextEditor) (found version
  "5.91.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  startcask/CMakeLists.txt:1 (find_package)
```

**Desktop (please complete the following information):**
 - OS: Fedora 36 with Cinnamon
 - Browser: chrome
 - Version: I don't know which is asked here, chrome? If so, it's 100.

**Fixing the errors:**
Add the followng to https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Fedora-35#compile-maui-shell-needs-mauikit-and-mauikit-filebrowsing:
```dnf
sudo dnf install kf5-kiconthemes-devel \
kf5-knotifications-devel \
kf5-kdoctools-devel \
kf5-krunner-devel \
kf5-knotifyconfig-devel \
kf5-kwallet-devel \
kf5-kdeclarative-devel \
kf5-kcrash-devel \
kf5-kglobalaccel-devel \
kf5-kdbusaddons-devel \
kf5-kwayland-devel \
kf5-kpeople-devel \
kf5-kactivities-stats-devel \
kf5-kactivities-devel \
kf5-prison-devel \
kf5-karchive-devel \
kf5-kunitconversion-devel \
kf5-kitemmodels-devel \
kf5-kinit-devel \
kf5-ktexteditor-devel \
kf5-kdesu-devel \
kf5-kded-devel \
phonon-qt5-devel \
polkit-devel \
polkit-qt5-1-devel
```
The first two (`kf5-kiconthemes-devel` and `kf5-knotifications-devel`) I don't actually know if they're needed, I found them here: https://github.com/KDAB/hotspot/issues/271. Probably not necessary but I installed them anways.

Please include them in the Wiki so others will not have to face this issue. Thanks!

**Comment by Macintosh98** [comment]
thanks worked for me, for me only "phonon-qt5-devel"  pakage was remain to install

**Comment by thetredev** [comment]
My Fedora install was nearly fresh when it comes to devel packages. You can always the steps in the Wiki with a fresh VM if you must.

**Comment by UriHerrera** [comment]
Wiki updated.
