### ISSUE TITLE
Fedora 36 error on Compile Maui Shell

### ISSUE THREAD

**Issue by GUFFYch** [Nitrux/maui-shell#38]
**Describe the bug**
have this error on ```Compile Maui Shell (needs MauiKit and MauiKit FileBrowsing)``` step
```
-- Could not set up the appstream test. appstreamcli is missing.
-- Found KF5: success (found suitable version "5.93.0", minimum required is "5.60") found components: I18n Service KIO 
CMake Error at plugins/casklib/CMakeLists.txt:75 (find_package):
  By not providing "FindMauiMan.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MauiMan", but
  CMake did not find one.

  Could not find a package configuration file provided by "MauiMan" with any
  of the following names:

    MauiManConfig.cmake
    mauiman-config.cmake

  Add the installation prefix of "MauiMan" to CMAKE_PREFIX_PATH or set
  "MauiMan_DIR" to a directory containing one of the above files.  If
  "MauiMan" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/dimmy/maui-shell/build/CMakeFiles/CMakeOutput.log".
```

here is also ``` /home/dimmy/maui-shell/build/CMakeFiles/CMakeOutput.log ``` output:
https://pastebin.com/xv6n2tT8 

**Screenshots**
![image](https://user-images.githubusercontent.com/53491867/169704184-2f6313cd-8d4a-46e1-8f0f-d5ac2dcfe4eb.png)

**Desktop (please complete the following information):**
```
OS: Fedora Linux 36 (Workstation Edition) x86_64  
DE: GNOME 42.0 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA GeForce GTX 1660 Ti Mobile 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
```

**Comment by milohr** [comment]
This is a new dependency. It is the Maui Settings Manager
https://github.com/Nitrux/maui-manager

**Comment by Justinzobel** [comment]
These instructions need updating then: https://github.com/Nitrux/maui-shell/wiki/Build-instructions-for-Fedora

**Comment by Vistaus** [comment]
How do I compile maui-manager? I tried to compile it the usual way, but Mauikit and Maui Shell report that they can't find it. Do I need a special cmake argument to compile Maui Manager?

**Comment by cniw** [comment]
yeah because the MauiMan library has been moved to reparated repo
from https://github.com/Nitrux/maui-manager/commit/0324a29b69dea1587ecd67702abcc1c2f4e05596
to https://invent.kde.org/camiloh/mauiman/-/commit/ca0bd103d32d44d1ffcfc6a22f27e504fa934132

for now here the build order:
1. https://invent.kde.org/camiloh/mauiman (MauiMan library and MauiManServer)
2. https://invent.kde.org/maui/mauikit
3. https://invent.kde.org/maui/mauikit-filebrowsing
4. https://github.com/Nitrux/maui-shell
5. https://github.com/Nitrux/maui-manager (optional, MauiSettings - Maui Settings Manager GUI Apps)

**Comment by Vistaus** [comment]
@cniw But that still doesn't explain how to compile mauiman. The usual cmake compilation doesn't work as MauiKit and Maui Shell still can't find mauiman.

**Comment by cniw** [comment]
```bash
git clone https://invent.kde.org/camiloh/mauiman.git
cd mauiman
cmake -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=/usr/lib
cmake --build build
cmake --install build
```

**Comment by Vistaus** [comment]
Thanks, that worked! 🙂
