### ISSUE TITLE
Maui Shell fails to start on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Vistaus** [Nitrux/maui-shell#43]
For a while now, it fails to start. If I run cask -r from a terminal, I get the following output:

```
~  INIT SCREEN MANAGER
 INIT THEME MANAGER
CSD QML SOURCXE QUrl("file:///usr/share/org.mauikit.controls/csd/Nitrux/CSD.qml")
CREATING INSTANCE OF MAUI APP
1 96 122.303 QRect(0,0 2560x1440) QSize(2560, 1440) QSize(2560, 1440)
QCommandLineParser: already having an option named "h"
QCommandLineParser: already having an option named "help-all"
QCommandLineParser: already having an option named "v"
Screen "DP-2" QRect(0,0 2560x1440) QSizeF(530, 300) DPI: log 96 phys 122.303 DPR 1
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:24:5: Type Screen unavailable
qrc:/qml/Screen.qml:176:32: Type StatusBar unavailable
KCrash: Application 'cask' crashing...
The Wayland connection experienced a fatal error: Invalid file descriptor
```

OS: openSUSE Tumbleweed
Maui Shell: latest git master
Other Maui components: latest git master

**Comment by Vistaus** [comment]
I tried to create a log file using the instructions in the readme, but it just comes up empty.

**Comment by Vistaus** [comment]
A few months have passed and it still doesn't launch, however, the output is different now:

```
~ startcask-wayland
PASHE 0000000
PASHE 0000000 /end
PASHE 111111111 /end
kf.coreaddons.kaboutdata: QGuiApplication::applicationDisplayName "" is out-of-sync with KAboutData::applicationData().displayName "cask_session"
kf.coreaddons.kaboutdata: QGuiApplication::applicationDisplayName "" is out-of-sync with KAboutData::applicationData().displayName "cask_session"
```

**Comment by Vistaus** [comment]
I finally got it to start now, however, the orientation is wrong (see #48) and the cursor only works in the regular Cask session, not the Wayland session. But it's already an improvement.

**Comment by UriHerrera** [comment]
> I finally got it to start now, however, the orientation is wrong (see #48) and the cursor only works in the regular Cask session, not the Wayland session. But it's already an improvement.

@Vistaus For the latter see https://github.com/Nitrux/maui-shell/issues/24

**Comment by Vistaus** [comment]
> > I finally got it to start now, however, the orientation is wrong (see #48) and the cursor only works in the regular Cask session, not the Wayland session. But it's already an improvement.
> 
> @Vistaus For the latter see #24

Thanks. I'll close this issue then and I hope #48 and #24 will be solved soon so that I can finally give Maui Shell a real chance! 🙂
