### ISSUE TITLE
module "QtMultimedia" is not installed

### ISSUE THREAD

**Issue by gab-luz** [Nitrux/maui-shell#44]
**Describe the bug**
When running the AppImage, I get the following error:
qrc:/qml/shell/ScreenshotArea.qml:3:1: module "QtMultimedia" is not installed
Lets remove MauiApp singleton instance

I've also tried installing all the qtmultimedia libraries.
I've also tried installing the libraries below:
sudo apt install \
libkf5i18n-dev \
libkf5kio-dev \
libkf5notifications-dev \
libkf5solid-dev \
libkf5syntaxhighlighting-dev \
libqt5svg5-dev \
libqt5x11extras5-dev \
libxcb-icccm4-dev \
libxcb-shape0-dev \
qml-module-qtgraphicaleffects \
qml-module-qtquick-controls2 \
qml-module-qtquick-shapes \
qtbase5-dev \
qtdeclarative5-dev \
qtquickcontrols2-5-dev \
libqt5multimedia5-plugins \
qml-module-qtmultimedia

**To Reproduce**
1. Run the AppImage file using terminal

**Expected behavior**
I've expected to run MauiShell

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 21

**Comment by probal31** [comment]
@gab-luz Please check the latest appimage from the release.
Have added the required dependency and should be solved now.

**Comment by gab-luz** [comment]
I'll close this issue because it's not asking for qtmultimedia anymore but I get new errors now.
