### ISSUE TITLE
Release PinePhone images

### ISSUE THREAD

**Issue by darkdragon-001** [Nitrux/maui-shell#46]
### Is your proposal related to a problem?

People would like to easily flash of to an sdcard and test it on the PinePhone. 

### Describe the solution you'd like

Image with Maui Shell and Maui apps readily flashable via dd to the PinePhone.

### Describe alternatives you've considered

Building myself is a big hurdle especially on slow hardware.

### Additional context

Demand is [high](https://forum.pine64.org/showthread.php?tid=16098).

**Comment by UriHerrera** [comment]
As it's mentioned in the [Wiki](https://github.com/Nitrux/maui-shell/wiki/What-is-Maui-Shell-(and-what-it-isn't)#what-maui-shell-is-not).

> 1. Maui Shell is not a Linux distribution.

Maui Shell is software that distributions can distribute. If your distribution doesn't package Maui Shell, please ask its maintainers. We already provide AppImages of this software.

**Comment by darkdragon-001** [comment]
I thought Nitrux is the reference distribution!? Can't you provide a Nitrux image for the PinePhone?

**Comment by UriHerrera** [comment]
@darkdragon-001 **_This repository_** is not the bug tracker for the distribution; this repository is for Maui Shell. Open an issue at the bug tracker [here](https://github.com/Nitrux/nitrux-bug-tracker) to make a feature request about the distribution.
