### ISSUE TITLE
ManjaroARM crash

### ISSUE THREAD

**Issue by luka177** [Nitrux/maui-shell#5]
**Describe the bug**
Cant start shell on manjaro arm

**To Reproduce**
1. Install manjaro arm
2. Build maui shell and kit
3. install them
4. try to run

**Expected behavior**
Maui shell must appear on screen

**Error**
```
[     0.051 d] Screen "" QRect(0,0 1080x2340) QSizeF(274, 594) DPI: log 100.089 phys 100.089 DPR 1
[     0.051 d] highest DPR 1 -> cursor size 32
[     0.578 W] QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7fdda04448), parent's thread is QThread(0x62aa4c6a00), current thread is QThread(0x62aa5734d0)
[     0.578 W] QObject::installEventFilter(): Cannot filter events for objects in a different thread.
[     0.586 W] Could not find any platform plugin
[     0.931 W] QQmlApplicationEngine failed to load component
[     0.931 W] qrc:/qml/main.qml:16:5: Type Screen unavailable
[     0.931 W] qrc:/qml/Screen.qml:112:32: Type StatusBar unavailable
[     0.931 W] qrc:/qml/shell/statusbar/StatusBar.qml:210:13: Type TogglesItem unavailable
[     0.931 W] qrc:/qml/shell/statusbar/items/toggles/TogglesItem.qml:66:17: Type NetworkToggle unavailable
[     0.931 W] qrc:/qml/shell/statusbar/items/toggles/sections/network/NetworkToggle.qml:11:1: Type ToggleTemplate unavailable
[     0.931 W] qrc:/qml/shell/statusbar/items/toggles/ToggleTemplate.qml:10:1: Type CardButton unavailable
[     0.931 W] qrc:/qml/shell/templates/CardButton.qml:39:18: Invalid property assignment: "hovered" is a read-only property
```

**Comment by luka177** [comment]
[log.txt](https://github.com/Nitrux/maui-shell/files/7785828/log.txt)
Attaching strace

**Comment by stephen304** [comment]
I'm also having an issue starting on Arch, I installed maui-shell-git from the aur (https://aur.archlinux.org/packages/maui-shell-git/)

When I run cask I get a black window and nothing happens. I tried to check for all the dependencies and it seems like I have the arch equivalent of everything that's listed. I also tried the cask session that shows up on my login screen but that just shows a black screen for a bit and then returns to login.

Cask output: https://gist.github.com/stephen304/912aaa7ae0a3bf0c306508c6e707fbf3#file-cask-log

**Comment by milohr** [comment]
> **Describe the bug** Cant start shell on manjaro arm
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install manjaro arm
> 
>     2. Build maui shell and kit
> 
>     3. install them
> 
>     4. try to run
> 
> 
> **Expected behavior** Maui shell must appear on screen
> 
> **Error**
> 
> ```
> [     0.051 d] Screen "" QRect(0,0 1080x2340) QSizeF(274, 594) DPI: log 100.089 phys 100.089 DPR 1
> [     0.051 d] highest DPR 1 -> cursor size 32
> [     0.578 W] QObject: Cannot create children for a parent that is in a different thread.
> (Parent is QGuiApplication(0x7fdda04448), parent's thread is QThread(0x62aa4c6a00), current thread is QThread(0x62aa5734d0)
> [     0.578 W] QObject::installEventFilter(): Cannot filter events for objects in a different thread.
> [     0.586 W] Could not find any platform plugin
> [     0.931 W] QQmlApplicationEngine failed to load component
> [     0.931 W] qrc:/qml/main.qml:16:5: Type Screen unavailable
> [     0.931 W] qrc:/qml/Screen.qml:112:32: Type StatusBar unavailable
> [     0.931 W] qrc:/qml/shell/statusbar/StatusBar.qml:210:13: Type TogglesItem unavailable
> [     0.931 W] qrc:/qml/shell/statusbar/items/toggles/TogglesItem.qml:66:17: Type NetworkToggle unavailable
> [     0.931 W] qrc:/qml/shell/statusbar/items/toggles/sections/network/NetworkToggle.qml:11:1: Type ToggleTemplate unavailable
> [     0.931 W] qrc:/qml/shell/statusbar/items/toggles/ToggleTemplate.qml:10:1: Type CardButton unavailable
> [     0.931 W] qrc:/qml/shell/templates/CardButton.qml:39:18: Invalid property assignment: "hovered" is a read-only property
> ```

Thats due to changes in MauiKit. You woudl need to always have Mauikit from master

**Comment by luka177** [comment]
I have newest commit already

**Comment by stephen304** [comment]
I also built mauikit from master as well as the shell from commit f0bef84293075b723172066e822607de364f0986 .

**Comment by nicolasdanelon** [comment]
I can't even build it on ArchLinux.. how do you guys did it?

**Comment by stephen304** [comment]
@nicolasdanelon I think the latest commit may have some dependency issue, but the commit before f0bef84 seems to work.

in the pkgbuild:
```
-source=(git+$url.git)
+source=(git+$url.git#commit=f0bef84)
```

**Comment by luka177** [comment]
Got it up. Needed to rebuild. Now its ok tho latest commit is broken, but that is not subject of this issue.
