### ISSUE TITLE
Failing to find MauiKitFileBrowsing4 when installing from AUR

### ISSUE THREAD

**Issue by piee-kun** [Nitrux/maui-shell#59]
**Describe the bug**
Installing from AUR doesn't install the right version of MauiKitFileBrowsing.

**To Reproduce**
Install maui-shell-git from AUR.
![image](https://github.com/Nitrux/maui-shell/assets/31517004/70a34f03-bfbc-4b55-8623-2e36c6fa1ea7)

**Comment by cniw** [comment]
should fixed now by this [commit `use qt6`](https://aur.archlinux.org/cgit/aur.git/commit/?h=mauikit-filebrowsing-git&id=85cc662079d2c85c0f262a352c5a43085322da4a) please try again reinstalling the `mauikit-filebrowsing-git` package
