### ISSUE TITLE
Build instructions for Fedora/RPM Based distributions.

### ISSUE THREAD

**Issue by JaydenDev** [Nitrux/maui-shell#9]
I want to try out MAUI shell myself on my Fedora 35 system. I can't build it though as the packages listed in the README are only found in Ubuntu. If there could be Fedora build instructions that'd be great.

**Comment by ruby-rust-perl** [comment]
Hey @JaydenDev those packages are also available in Fedora but not in the same name given there.  First, try to install without any of the given dependencies. It will throw the errors.
For dependencies starting with `KF5`, install all of them using `sudo dnf install kf5-k*-devel`
I installed all the necessary `qt5` files via `sudo dnf install qt5-*`. I have a linker problem though (#10)

**Comment by JaydenDev** [comment]
@ruby-rust-perl I see, while I'm running that. Is there any way to add it to the desktop environment list of GDM/SDDM.

**Comment by JaydenDev** [comment]
@ruby-rust-perl build failure
```
CMake Error at plugins/casklib/CMakeLists.txt:73 (find_package):
  By not providing "FindMauiKit.cmake" in CMAKE_MODULE_PATH this project has                
  asked CMake to find a package configuration file provided by "MauiKit", but               
  CMake did not find one.                                                                   
                                                                                            
  Could not find a package configuration file provided by "MauiKit" with any                
  of the following names:                                                                   
                                                                                            
    MauiKitConfig.cmake                                                                     
    mauikit-config.cmake                                                                    
                                                                                            
  Add the installation prefix of "MauiKit" to CMAKE_PREFIX_PATH or set                      
  "MauiKit_DIR" to a directory containing one of the above files.  If                       
  "MauiKit" provides a separate development package or SDK, be sure it has                  
  been installed.      
```

**Comment by JaydenDev** [comment]
i forgot to install mauikit..

**Comment by JaydenDev** [comment]
installed but still doesn't compile.

**Comment by UriHerrera** [comment]
> installed but still doesn't compile.

@JaydenDev Maui Shell needs MauiKit from Git master.

**Comment by JaydenDev** [comment]
> > installed but still doesn't compile.
> 
> @JaydenDev Maui Shell needs MauiKit from Git master.

I just clone it as a sub-module?

**Comment by JaydenDev** [comment]
I compiled mauikit from source and it still doesn't compile maui-shell.

**Comment by JaydenDev** [comment]
> > installed but still doesn't compile.
> 
> @JaydenDev Maui Shell needs MauiKit from Git master.
I have compiled MauiKit from source but Maui Shell still fails to compile with the same error

**Comment by milohr** [comment]
> > > installed but still doesn't compile.
> > 
> > 
> > @JaydenDev Maui Shell needs MauiKit from Git master.
> > I have compiled MauiKit from source but Maui Shell still fails to compile with the same error

Did you set the cmake prefix path to /usr? Cab you share the locations where mauikit was installed after you did sudo make install?

**Comment by JaydenDev** [comment]
> > > > installed but still doesn't compile.
> > > 
> > > 
> > > @JaydenDev Maui Shell needs MauiKit from Git master.
> > > I have compiled MauiKit from source but Maui Shell still fails to compile with the same error
> 
> Did you set the cmake prefix path to /usr? Cab you share the locations where mauikit was installed after you did sudo make install?

I recently cleaned my home dir I'll see what bits and peices of info I can find.

**Comment by JaydenDev** [comment]
I set all the required prefixes via the command in the README, haven't changed nothing or went outside the instructions.

**Comment by UriHerrera** [comment]
```
#	Build MauiKit Fedora 35

sudo dnf install cmake
sudo dnf install extra-cmake-modules

#	Qt5 Dependencies

sudo dnf install qt5-qtbase-devel
sudo dnf install qt5-qtx11extras-devel
sudo dnf install qt5-qtdeclarative-devel
sudo dnf install qt5-qtquickcontrols2-devel
sudo dnf install qt5-qtsvg-devel

#	KF5 Dependencies

sudo dnf install kf5-kwindowsystem-devel
sudo dnf install kf5-kcoreaddons-devel
sudo dnf install kf5-k18n-devel
sudo dnf install kf5-kconfig-devel
sudo dnf install kf5-knotifications-devel
sudo dnf install kf5-kidletime-devel

#	XCB Dependences

sudo dnf install xcb-util-wm-devel

#	Compile MauiKit

cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BSYMBOLICFUNCTIONS=OFF -DQUICK_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu ..

make

sudo make install
```

```
#	Build Maui Shell Fedora 35

sudo dnf install qt5-qtwayland-devel

#	KF5 Dependencies

sudo dnf install kf5-kservice-devel
sudo dnf install kf5-kio-devel
sudo dnf install kf5-kidletime-devel

#	Compile MauiKit Filebrowsing  (needs MauiKit and KIO)

cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BSYMBOLICFUNCTIONS=OFF -DQUICK_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/MauiKit ..

make

sudo make install

#	Compile Maui Shell (needs MauiKit and MauiKit FIlebrowsing)

cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BSYMBOLICFUNCTIONS=OFF -DQUICK_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib/x86_64-linux-gnu -DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/cmake/MauiKit;/usr/lib/x86_64-linux-gnu/cmake/MauiKitFileBrowsing"  ..

make

sudo make install

#	Runtime Dependencies

sudo dnf install bluedevil
sudo dnf install kf5-bluez-qt
sudo dnf install kf5-kirigami2
sudo dnf install kf5-plasma
sudo dnf install plasma-nm
sudo dnf install plasma-pa
```

![VirtualBox_Fedora_21_01_2022_20_22_33](https://user-images.githubusercontent.com/3053525/150621375-dbf50686-26e7-49be-9aac-df207fb78767.png)

**Comment by JaydenDev** [comment]
I had everything compiled and installed that's required at compile time and it still seems to say I don't have MauiKit instaleled

**Comment by UriHerrera** [comment]
@JaydenDev If you're referring to an error where CMake says it can't find the file `MauiKitConfig.cmake` _**Please** follow the instructions above._

**Comment by JaydenDev** [comment]
What I noticed is that I haven't compiled mauikit-filebrowsing, doing that now.

**Comment by JaydenDev** [comment]
```
/usr/bin/ld: cannot find -lMauiKit
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/MauiKitFileBrowsing.dir/build.make:772: bin/libMauiKitFileBrowsing.so.2.1.0] Error 1
make[2]: Leaving directory '/home/jmwills/mauikit-filebrowsing/build'
make[1]: *** [CMakeFiles/Makefile2:239: src/CMakeFiles/MauiKitFileBrowsing.dir/all] Error 2
make[1]: Leaving directory '/home/jmwills/mauikit-filebrowsing/build'
make: *** [Makefile:149: all] Error 2
```

ugh...

**Comment by JaydenDev** [comment]
what ```ld -lMauiKit``` shows
```
/usr/bin/ld: cannot find -lMauiKit
```

**Comment by UriHerrera** [comment]
@JaydenDev Once more, I kindly ask you to *please follow the instructions above*. Start with a clean build and copy and paste the commands.

Also, Please do not create spam comments; you can edit your original comment and add whatever else you want to it.

I'm closing this issue as instructions are available.

**Comment by JaydenDev** [comment]
> @JaydenDev Once more, I kindly ask you to _please follow the instructions above_. Start with a clean build and copy and paste the commands.
> 
> Also, Please do not create spam comments; you can edit your original comment and add whatever else you want to it.
> 
> I'm closing this issue as instructions are available.

i followed them all...

**Comment by JaydenDev** [comment]
Status: **Errors**

**Comment by UriHerrera** [comment]
@JaydenDev CMake didn't ask for `libcanberra`, so I didn't need to install its `-devel` package. But, if you do need it (for any reason whatsoever), then install it.

**Comment by JaydenDev** [comment]
> @JaydenDev CMake didn't ask for `libcanberra` when I built it a few minutes ago, so I didn't need to install its `-devel` package. But, if you do need it (for any reason whatsoever), then install it.

in your latest commit i see you've changed the maui filebrowsing clone command to clone from master branch instead of stable, should I recompile mauikit filebrowsing from the master branch?

**Comment by UriHerrera** [comment]
@JaydenDev Yes, MauiKit, FileBrowsing, and Maui Shell need to be from the `master` branch.

**Comment by JaydenDev** [comment]
> @JaydenDev Yes, MauiKit, FileBrowsing, and Maui Shell need to be from the `master` branch.

I've done maui kit and maui shell cloned from master so i'll redo mauikit filebrowsing

**Comment by JaydenDev** [comment]
since i'm installing system updates I cannot do package installation rn

**Comment by JaydenDev** [comment]
So, cloning from master branch made it get past the error.

**Comment by JaydenDev** [comment]
New error on runtime
```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:16:5: Type Screen unavailable
qrc:/qml/Screen.qml:112:32: Type StatusBar unavailable
qrc:/qml/shell/statusbar/StatusBar.qml:200:13: Type TogglesItem unavailable
qrc:/qml/shell/statusbar/items/toggles/TogglesItem.qml:67:17: Type NetworkToggle unavailable
qrc:/qml/shell/statusbar/items/toggles/sections/network/NetworkToggle.qml:11:1: Type ToggleTemplate unavailable
qrc:/qml/shell/statusbar/items/toggles/ToggleTemplate.qml:29:9: Cannot assign to non-existent property "isMask"
[1]    81354 segmentation fault (core dumped)  cask
```
not sure what this is..
